name: Update Spotify Now Playing

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Spotify Data
        run: |
          curl -X "GET" "https://api.spotify.com/v1/me/player/currently-playing" \
            -H "Authorization: Bearer ${{ secrets.SPOTIFY_ACCESS_TOKEN }}" \
            -o now-playing.json
          jq '.item.name + " - " + .item.artists[0].name' now-playing.json > now-playing.txt

      - name: Update README
        run: |
          sed -i "s|🎵 Now Playing: .*|🎵 Now Playing: $(cat now-playing.txt)|" README.md

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated Now Playing"
          git push
